spring.application.name=hyunwoo

# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 URL (JDBC \uD615\uC2DD)
spring.datasource.url=${database.url}

# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC811\uC18D \uC0AC\uC6A9\uC790\uBA85
spring.datasource.username=${database.user.name}

# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC811\uC18D \uBE44\uBC00\uBC88\uD638
spring.datasource.password=${database.user.password}

# JDBC \uB4DC\uB77C\uC774\uBC84 \uD074\uB798\uC2A4 MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Google Mail STMP \uC0AC\uC6A9\uC744 \uC704\uD55C \uC0AC\uC6A9
# \uCC38\uACE0: https://velog.io/@kyungmin/Spring-%EC%9D%B4%EB%A9%94%EC%9D%BC-%EC%9D%B8%EC%A6%9DGoogle
spring.mail.host=${mail.host}
spring.mail.port=${mail.port}
spring.mail.username=${mail.name}
spring.mail.password=${mail.password}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.auth-code-expiration-millis=1800000

# redis \uC124\uC815
spring.data.redis.host=${redis.host}
spring.data.redis.port=${redis.port}
spring.data.redis.password=${redis.password}