spring.application.name=hyunwoo
spring.config.import=optional:classpath:secret.properties

# xml \uD328\uD0A4\uC9C0 \uACBD\uB85C \uBA85\uC2DC, xml \uC778\uC2DD \uACBD\uB85C
mybatis.mapper-locations=classpath:com/sandbox/mapper/*.xml

# MyBatis \uC124\uC815, \uD328\uD0A4\uC9C0 \uBA85\uC744 \uC801\uC5B4\uC918\uC57C\uD558\uB294\uB370 \uC0DD\uB7B5 \uAC00\uB2A5\uD558\uAC8C \uD574\uC90C -> configuration
mybatis.type-aliases-package=com.sandbox.hyunwoo.crud.dto, com.sandbox.hyunwoo.paging.dto
# \uAD00\uB840 \uBD88\uC77C\uCE58, DB\uB294 _\uB85C \uB418\uC5B4\uC788\uC73C\uBA74 camelCase\uB85C \uBC14\uAFD4\uC90C
mybatis.configuration.map-underscore-to-camel-case=true
# \uC5D0\uB7EC \uD655\uC778
logging.level.com.ssafy.sandbox.crud.repository=trace

# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 URL (JDBC \uD615\uC2DD)
spring.datasource.url=${database.url}

# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC811\uC18D \uC0AC\uC6A9\uC790\uBA85
spring.datasource.username=${database.user.name}

# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC811\uC18D \uBE44\uBC00\uBC88\uD638
spring.datasource.password=${database.user.password}

# JDBC \uB4DC\uB77C\uC774\uBC84 \uD074\uB798\uC2A4 MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver